### ISSUE TITLE
Publishign a stream using https://quic.video/publish/ does not work

### ISSUE THREAD

**Issue by Quackdoc** [kixelated/moq-js#133]
When I try it via chromium I get this error thrown to the console

```
publish/:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
fail.880fdaa3.js:1 established connection: version=4278955266
publish.8a18f63f.js:1 failed to run video packer:  TypeError: n.encode is not a function
    at #r (publish.8a18f63f.js:1:1850)
    at Object.write (publish.8a18f63f.js:1:1649)
(anonymous) @ publish.8a18f63f.js:1
Promise.catch
publish @ publish.8a18f63f.js:1
(anonymous) @ publish.8a18f63f.js:1
be @ web.6fcd8348.js:1
N @ web.6fcd8348.js:1
O @ web.6fcd8348.js:1
Ae @ web.6fcd8348.js:1
(anonymous) @ web.6fcd8348.js:1
M @ web.6fcd8348.js:1
xe @ web.6fcd8348.js:1
M @ web.6fcd8348.js:1
xe @ web.6fcd8348.js:1
M @ web.6fcd8348.js:1
ie @ web.6fcd8348.js:1
s @ web.6fcd8348.js:1
K.$$click @ publish.8a18f63f.js:1
ce @ web.6fcd8348.js:1
```

**Comment by kixelated** [comment]
I'll take a look tomorrow, sorry about that. I made some breaking changes recently and maybe it only partially deployed.

**Comment by kixelated** [comment]
Uh so publishing wasn't even close to working after the last few rounds of changes. I fixed some bugs in #134 but tbh I'm instead going to focus my energy on the Rust version. I just don't want to work in Javascript any longer...

ex. one of the bugs was `[] !== []`. Why does this language exist.

**Comment by Quackdoc** [comment]
That's quite understandable, is it safe to say the direction that was ponderered in t[o wasm, or not to wasm](https://quic.video/blog/to-wasm/) has been answered? :D

I have no qualms with the tech, I initially just wanted a showcase that my friends can use to demo and try out the latency and stuff. Will the moq wasm stuff be available as a demo on the website? I can personally self host for some friends, but having it on the webpage would be a lot nicer.

**Comment by kixelated** [comment]
> That's quite understandable, is it safe to say the direction that was ponderered in t[o wasm, or not to wasm](https://quic.video/blog/to-wasm/) has been answered? :D
> 
> I have no qualms with the tech, I initially just wanted a showcase that my friends can use to demo and try out the latency and stuff. Will the moq wasm stuff be available as a demo on the website? I can personally self host for some friends, but having it on the webpage would be a lot nicer.

Yeah, playback support has been merged and I'll implement contribution now.
